/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        display:    ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md':  ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg':  ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
        'label-sm':   ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display':      ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg':  ['32px', { lineHeight: '40px', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '800' }],
        'headline-md':  ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg':      ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md':      ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-mono':   ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm':     ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      colors: {
        'primary':                    '#b4ffec',
        'on-primary':                 '#00382f',
        'primary-container':          '#8de4d0',
        'on-primary-container':       '#006759',
        'primary-fixed':              '#9bf3de',
        'primary-fixed-dim':          '#7fd6c3',
        'on-primary-fixed':           '#00201a',
        'on-primary-fixed-variant':   '#005145',
        'secondary':                  '#d0bfee',
        'on-secondary':               '#362a50',
        'secondary-container':        '#4d4068',
        'on-secondary-container':     '#beaddc',
        'secondary-fixed':            '#ebddff',
        'secondary-fixed-dim':        '#d0bfee',
        'on-secondary-fixed':         '#211439',
        'on-secondary-fixed-variant': '#4d4068',
        'tertiary':                   '#ffefce',
        'on-tertiary':                '#3e2e00',
        'tertiary-container':         '#f6d06e',
        'on-tertiary-container':      '#725800',
        'tertiary-fixed':             '#ffdf92',
        'tertiary-fixed-dim':         '#e7c262',
        'on-tertiary-fixed':          '#241a00',
        'on-tertiary-fixed-variant':  '#594400',
        'error':                      '#ffb4ab',
        'on-error':                   '#690005',
        'error-container':            '#93000a',
        'on-error-container':         '#ffdad6',
        'background':                 '#131313',
        'on-background':              '#e5e2e1',
        'surface':                    '#131313',
        'surface-dim':                '#131313',
        'surface-bright':             '#393939',
        'surface-variant':            '#353534',
        'surface-container-lowest':   '#0e0e0e',
        'surface-container-low':      '#1c1b1b',
        'surface-container':          '#201f1f',
        'surface-container-high':     '#2a2a2a',
        'surface-container-highest':  '#353534',
        'on-surface':                 '#e5e2e1',
        'on-surface-variant':         '#bdc9c5',
        'outline':                    '#88938f',
        'outline-variant':            '#3e4946',
        'inverse-surface':            '#e5e2e1',
        'inverse-on-surface':         '#313030',
        'inverse-primary':            '#006b5c',
        'surface-tint':               '#7fd6c3',
      },
      spacing: {
        'xs':             '8px',
        'sm':             '16px',
        'md':             '24px',
        'lg':             '32px',
        'xl':             '48px',
        'gutter':         '20px',
        'margin-mobile':  '16px',
        'margin-desktop': '40px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      boxShadow: {
        'neo':    '4px 4px 0px 0px rgba(0,0,0,1)',
        'neo-sm': '2px 2px 0px 0px rgba(0,0,0,1)',
        'neo-lg': '6px 6px 0px 0px rgba(0,0,0,1)',
        'neo-xl': '8px 8px 0px 0px rgba(0,0,0,1)',
        'neo-t':  '0px -4px 0px 0px rgba(0,0,0,1)',
      },
      animation: {
        'fade-up':    'fadeUp 0.4s ease forwards',
        'fade-in':    'fadeIn 0.3s ease forwards',
        'bounce-dot': 'bounceDot 1.4s ease-in-out infinite',
      },
      keyframes: {
        fadeUp:    { from: { opacity: 0, transform: 'translateY(12px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        fadeIn:    { from: { opacity: 0 }, to: { opacity: 1 } },
        bounceDot: { '0%,80%,100%': { transform: 'scale(0)' }, '40%': { transform: 'scale(1)' } },
      }
    }
  },
  plugins: []
}
